library(shiny)
library(DT)
library(plotly)
ui <- fluidPage(
  sidebarLayout(
    sidebarPanel(
      fileInput("file1", "Upload the High Level Statistics file Generated by seQcReporter",
                accept = c(
                  "text/csv",
                  "text/tab-separated-values,text/plain",
                  ".txt")
      ),
      fileInput("file2", "Upload the Centrifuge Summary File",
                accept = c(
                  "text/csv",
                  "text/tab-separated-values,text/plain",
                  ".txt")
      ),
      tags$script('$( "#file1" ).on( "click", function() { this.value = null; });'),
      tags$script('$( "#file2" ).on( "click", function() { this.value = null; });'),
      helpText("Controls for Exploratory Plotting."),
      uiOutput("choose_xaxis"),
      uiOutput("choose_yaxis"),
      uiOutput("choose_color"),
      checkboxInput("overview_mode", "Show overview of data", FALSE),
      checkboxInput("fit_lm", "Fit linear regression", FALSE),
      helpText("Controls for Grouped Data Plotting."),
      uiOutput("choose_group"),
      uiOutput("choose_variable"),
      uiOutput("choose_plottype"),
      checkboxInput("facet", "Split by Group.", FALSE),
      helpText("Controls for Centrifuge Heatmap."),
      uiOutput("choose_tax_class"),
      checkboxInput("quantile_mode", "Quantile Mode for Centrifuge Results Heatmap", FALSE)
      ),
    mainPanel(
    htmltools::div(style = "display:inline-block", plotlyOutput("mainPlot", width = 1000, height = 700)),
    br(),
    htmltools::div(style = "display:inline-block", plotlyOutput("projPlot", width = 1000, height = 700)),
    br(),
    htmltools::div(style = "display:inline-block", plotlyOutput("centPlot", width = 1000, height = 500)),
    br(),
    DTOutput("contents") # table stopped working so I took it out!
    )
  )
)